lint: fix errors, ignore errcheck for providerserver.Serve
main.go:15:22: Error return value of `providerserver.Serve` is not checked (errcheck)
	providerserver.Serve(context.Background(), hostingde.New, providerserver.ServeOpts{
	                    ^
hostingde/records.go:31:18: func `(*Client).getRecord` is unused (unused)
func (d *Client) getRecord(findRequest RecordsFindRequest) (*DNSRecord, error) {
                 ^
hostingde/zone_resource.go:40:6: type `zoneSOAResourceModel` is unused (unused)
type zoneSOAResourceModel struct {
     ^
hostingde/zones.go:14:18: func `(*Client).findZoneConfig` is unused (unused)
func (c *Client) findZoneConfig(tfCtx context.Context, findRequest ZoneConfigsFindRequest) (*ZoneConfig, error) {
                 ^
hostingde/zones.go:50:18: func `(*Client).listZoneConfigs` is unused (unused)
func (c *Client) listZoneConfigs(findRequest ZoneConfigsFindRequest) (*ZoneConfigsFindResponse, error) {
                 ^
hostingde/zones.go:71:6: func `getZoneConfig` is unused (unused)
func getZoneConfig(tfCtx context.Context, zoneId string, c *Client) (*ZoneConfig, error) {
     ^
hostingde/client.go:29:15: SA5011: possible nil pointer dereference (staticcheck)
		accountId:  *accountId,
		            ^
hostingde/client.go:36:5: SA5011(related information): this check suggests that the pointer can be nil (staticcheck)
	if accountId != nil {
	   ^
hostingde/client.go:30:15: SA5011: possible nil pointer dereference (staticcheck)
		authToken:  *authToken,
		            ^
hostingde/client.go:33:5: SA5011(related information): this check suggests that the pointer can be nil (staticcheck)
	if authToken != nil {
	   ^